name: Release PDF

on:
  pull_request:
    branches: [main]
    paths: 'docs/README.md'

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache@v2
        id: node_modules_cache_id
        with:
          path: |
            node_modules
          key: node-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      - name: Run yarn install
        run: yarn --check-files --frozen-lockfile --non-interactive
      - name: Cache workspace
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: node-${{ github.sha }}
  release:
    name: Release PDF
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs:
      - setup
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Restore workspace cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: node-${{ github.sha }}
      - name: Build PDF
        run: make build-pdf
      - name: Create a draft release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ github.event.pull_request.title }}
          draft: true
          fail_on_unmatched_files: true
          files: docs/README.pdf
          name: Release ${{ github.ref }}
