name: Create issue

on:
  schedule:
    - cron: "0 0 1 */3 *"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  build:
    name: Create issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5 # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
