name: Release PDF

on:
  pull_request:
    branches: [main]
    paths: ['docs/README.md']
  workflow_dispatch:

jobs:
  release:
    name: Release PDF
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Run oven-sh/setup-bun
        uses: oven-sh/setup-bun@d3603274aca5625baad52ec06108517a089cdd00 # v1
      - name: Run bun install
        run: bun install --no-save
      - name: Run bun build:pdf
        run: bun build:pdf
      - name: Create a draft release
        uses: softprops/action-gh-release@d99959edae48b5ffffd7b00da66dcdb0a33a52ee # v2
        with:
          body: ${{ github.event.pull_request.title }}
          draft: true
          fail_on_unmatched_files: true
          files: docs/README.pdf
          name: Release ${{ github.ref }}
